Multi unindex
kontera-technologies/meeseeks-db pull request #7
Opened 2020-09-29 10:53 UTC by amirmamo314

2020-09-29 12:56 UTC, gilburd requested changes

2020-10-04 10:36 UTC, amirmamo314 commented on src/meeseeks_db/core.clj
> +   (wcar conn (dorun (map #(car/get (str "id:" %)) id)))))
changed

2020-10-04 10:37 UTC, amirmamo314 commented on src/meeseeks_db/core.clj
> +(defn default-multi-id->conn [db id]
removed

2020-11-11 07:27 UTC, gilburd commented on src/meeseeks_db/core.clj
> +            (doseq [[iid_i index-pairs_i] iid-index-pairs]
can't the conn be outside the doseq using 1 connection for all `iid-index-pairs`?

2020-11-29 14:42 UTC, amirmamo314 commented on src/meeseeks_db/core.clj
> +     (let [iid_keys (doall (map #(str "id:" %) id))
unnecessary. removed every doall in multi functions and all tests pass successfully

2020-12-05 17:53 UTC, amirmamo-kontera submitted a review, later dismissed

2020-12-05 18:03 UTC, amirmamo-kontera submitted a review, later dismissed

2020-12-07 10:03 UTC, gilburd approved these changes

2020-12-07 10:03 UTC, merged